name: Merged main

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  merged_main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Get Pull Request Url
        uses: actions/github-script@v2
        id: set-pr-url
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.html_url

      - name: Get Pull Request Title
        uses: actions/github-script@v2
        id: set-pr-title
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.title

      - name: Send Notification Merged main
        run: |
          PAYLOAD=$(cat << EOF
            payload={
              'channel': '#kaihatsu',
              'username': 'MergedMain',
              'attachments': [{
                'fallback': 'This is merged notion attachment.',
                'color': 'good',
                'pretext': 'Mainにマージされました。',
                'title': '${{ steps.set-pr-title.outputs.result }}',
                'title_link': '${{ steps.set-pr-url.outputs.result }}',
              }],
              'icon_emoji': ':custard:'
            }
          EOF
          )
          curl -X POST --data-urlencode "$PAYLOAD" https://hooks.slack.com/services/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
